### ISSUE TITLE
Week 4 Breakdown

### ISSUE THREAD

**Issue by ella-irene** [UBC-MDS/DSCI-532_2024_18_VancouverAirbnbPrices#74]
**Alysen**

- [x] Fixed the default filter @ella-irene 
- [x] Added tooltip @ella-irene 
- [ ] When there is no filter that matches the search result: return empty Vancouver map and print "no data match your criteria" @ella-irene , @Kierst01 
- [ ] Add units to forecast price axis title @wenyunie 
- [ ] Change data range to be more intuitive @jlee2843 
- [ ] Change menu mouse overs to white instead of translucent white @jlee2843 
- [ ] Add example to prediction enterbox @jlee2843 

**Weilin**

- [x] Change the number of beds + number of bathrooms + room type to have multiple selections @Kierst01 

**Aishwarya**

- [ ] Add a disclaimer to the prediction tab to explain that the prediction works best in Vancouver @jlee2843 
- [ ] Investigate summary chart labels

**Milestone 4 Requirements**
- [ ] Breakout data processing into data processing file @jlee2843 
- [x] Refinement (5) - Done with other improvements
- [x] Favicon - shoutout Jenny for creating 
- [ ] Update gif animation 
- [ ] Get rid of the plotly toolbar from summary stats @jlee2843 
- [x] Reflection @Kierst01 

**Optional**
- [ ] Docstrings @ella-irene  if time permits

**Meeting**

- Work on fixes until Friday at NOON. Meet on slack @12:00 Friday to discuss where we are at and what still need to be done.
